name: grocery_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  badges: ^3.0.3
  flutter_svg: ^1.1.6
  flutter_staggered_grid_view: ^0.6.2
  fluttertoast: ^8.0.9
  http: ^0.13.5
  flutter_form_builder: ^7.8.0
  email_validator: ^2.1.17
  url_launcher: ^6.1.10
  pin_code_text_field: ^1.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/img/
    - assets/images/categories_images/
    - assets/images/grocery_images/
    - assets/images/beverages_images/
    - assets/icons/
    - assets/icons/account_icons/
    - assets/fonts/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
        - asset: assets/fonts/gilroy/Gilroy-Bold.otf